//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSecurityInspectClientService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADC_StatusCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADC_StatusCode()
        {
            this.ADC_Status = new HashSet<ADC_Status>();
        }
    
        public int ADC_ProcessStatus { get; set; }
        public string ADC_Descript { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADC_Status> ADC_Status { get; set; }
    }
}
