//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSecurityInspectClientService.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoSecurityInspectClientEntities : DbContext
    {
        public AutoSecurityInspectClientEntities()
            : base("name=AutoSecurityInspectClientEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADC_PushData> ADC_PushData { get; set; }
        public virtual DbSet<ADC_Status> ADC_Status { get; set; }
        public virtual DbSet<ADC_StatusCode> ADC_StatusCode { get; set; }
    }
}
