var LOG_LEVEL_VERBOSE = 0
var LOG_LEVEL_INFO = 1
var LOG_LEVEL_DEBUG = 2
var LOG_LEVEL_WARN = 3
var LOG_LEVEL_ERROR = 4

var APPLICATION_SERVER_PUBLIC_KEY = "BNryFoXl4sl4CY1Sx5IcNisuc9ROob4h_kPQnw3D1vKjDR8V1GvZnxRLiH98SrOQvHxXZ05ibGR-3BD8EIGDcMM"